name: Sedstart1

on:
  workflow_dispatch:

jobs:
  sedstart:
    runs-on: ubuntu-latest
    steps:
      - name: Running Sedstart
        uses: sedstart/runlocal@v1
        with:
          api_key: ${{ secrets.SEDSTART_KEY }}
          project_id: 612
          test_id: 4888
          profile_id: 1017
          browser: chrome
          headless: false
          environment: QA
